spring:
  #数据源
  datasource:
    url: jdbc:mysql://192.168.1.144:3306/spring?serverTimezone=Asia/Shanghai
    username: root
    password: Aimer
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JSP渲染Web视图
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates

  mvc:
#     put delete
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: 50MB
      #设置单次请求文件的总大小
      max-request-size: 50MB

# 扫描mapper.xml
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# 把日志打印到控制台
logging:
  level:
    com.yr.mapper: DEBUG


fdfs:
  connect-timeout: 200
  so-timeout: 200
  thumb-image:
    width: 150
    height: 150
  tracker-list: 192.168.1.231:22122,192.168.1.232:22122,192.168.1.233:22122